Remove the excessive server stopping and only-cleanup on purge when this is the last MySQL package (Closes: #858941)

diff --git a/debian/mariadb-server-10.0.prerm b/debian/mariadb-server-10.0.prerm
--- a/debian/mariadb-server-10.0.prerm
+++ b/debian/mariadb-server-10.0.prerm
@@ -8,3 +8,14 @@ if [ -n "$DEBIAN_SCRIPT_DEBUG" ]; then set -v -x; DEBIAN_SCRIPT_TRACE=1; fi
 ${DEBIAN_SCRIPT_TRACE:+ echo "#42#DEBUG# RUNNING $0 $*" 1>&2 }
 
 #DEBHELPER#
+
+# If MySQL server is still running let the admin do it himself. No
+# database directories should be removed while the server is running!
+# Another mysqld in e.g. a different chroot is fine for us.
+if pidof -c /usr/sbin/mysqld 2>/dev/null; then
+  echo "There is a MySQL server running, but we failed in our attempts to stop it." 1>&2
+  echo "Stop it yourself and try again!" 1>&2
+  exit 1
+fi
+
+exit 0
